services:
  - type: web
    name: eventscope
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
